Migrate `CBit` ops from `QUIR` to `OQ3` dialect (Part 1)
N.B. `variable_elimination3.mlir` currently failing due to:
```
error: failed to legalize operation 'oq3.assign_cbit_bit' that
was explicitly marked illegal
```